// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZgoxGko8dPbLfFfXo7zpypXc6BKuWvQ',
    appId: '1:485936875863:web:ee962c4b0c35bd204ed612',
    messagingSenderId: '485936875863',
    projectId: 'foodie-app-6e30f',
    authDomain: 'foodie-app-6e30f.firebaseapp.com',
    storageBucket: 'foodie-app-6e30f.appspot.com',
    measurementId: 'G-DQCQKGBWNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN86cetEoejis5qFT0z4TIQ8PMygJRmDM',
    appId: '1:485936875863:android:9396b5ab2bac4a324ed612',
    messagingSenderId: '485936875863',
    projectId: 'foodie-app-6e30f',
    storageBucket: 'foodie-app-6e30f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdKSu4XZloRCVUookHY0biubua1kf7XO0',
    appId: '1:485936875863:ios:8811f517f8b164d44ed612',
    messagingSenderId: '485936875863',
    projectId: 'foodie-app-6e30f',
    storageBucket: 'foodie-app-6e30f.appspot.com',
    iosBundleId: 'com.example.foodieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdKSu4XZloRCVUookHY0biubua1kf7XO0',
    appId: '1:485936875863:ios:8811f517f8b164d44ed612',
    messagingSenderId: '485936875863',
    projectId: 'foodie-app-6e30f',
    storageBucket: 'foodie-app-6e30f.appspot.com',
    iosBundleId: 'com.example.foodieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZgoxGko8dPbLfFfXo7zpypXc6BKuWvQ',
    appId: '1:485936875863:web:53db2d27177e86d64ed612',
    messagingSenderId: '485936875863',
    projectId: 'foodie-app-6e30f',
    authDomain: 'foodie-app-6e30f.firebaseapp.com',
    storageBucket: 'foodie-app-6e30f.appspot.com',
    measurementId: 'G-CKHZBZMHFJ',
  );
}
